# If additional kubelet args specified write them to env
- name: Kubernetes | Write Kubelet Env File - CCM
  template:
    src: kubelet.j2
    dest: /etc/sysconfig/kubelet
    owner: root
    group: root
    mode: 0644
  when: kubernetes.kubeletArgs is defined
  tags:
    - ccm

# Restart the kubelet
- name: Kubernetes | Restart the kubelet
  systemd:
    name: kubelet
    state: restarted
  tags:
    - ccm

# Generate tolerations
- name: Kubernetes | Generate CCM tolerations
  register: tolerations
  command: "kubectl taint node {{ item }} node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule"
  when: "'root_cluster' in group_names"
  with_inventory_hostnames:
    - all
  tags:
    - ccm

- name: DEBUG
  debug:
    msg: "{{ tolerations }}"
  tags:
    - ccm

# # Apply Tolerations
# - name: Kubernetes | Apply CCM tolerations
#   command:
